# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('organisations', '0003_organisationsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='site',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
    ]
