# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_auto_20161207_1529'),
        ('sections', '0002_section_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='slug',
            field=models.SlugField(default='foo', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set([('slug', 'organisation')]),
        ),
    ]
