# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_section_is_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='is_private',
        ),
        migrations.AddField(
            model_name='section',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='private?'),
        ),
    ]
