# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicmember',
            name='roles',
            field=models.PositiveSmallIntegerField(choices=[(100, 'Owner'), (50, 'Editor'), (30, 'Contributor'), (20, 'Member'), (10, 'Observer')], default=20),
        ),
    ]
