# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_topic_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicmember',
            name='created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='topicmember',
            name='modified',
            field=models.DateTimeField(null=True),
        ),
    ]
