# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_auto_20161207_1529'),
        ('topics', '0003_topic_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(default='foo', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topic',
            name='created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='modified',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set([('slug', 'organisation')]),
        ),
    ]
