# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'get_latest_by': 'published', 'ordering': ['-published'], 'verbose_name': 'article', 'verbose_name_plural': 'articles'},
        ),
        migrations.AddField(
            model_name='article',
            name='comment_count',
            field=models.IntegerField(default=0, verbose_name='comment count'),
        ),
        migrations.AddField(
            model_name='article',
            name='comment_enabled',
            field=models.BooleanField(default=True, help_text='Allows comments if checked.', verbose_name='comments enabled'),
        ),
        migrations.AddField(
            model_name='article',
            name='lead',
            field=models.TextField(blank=True, help_text='Lead paragraph', verbose_name='lead'),
        ),
        migrations.AddField(
            model_name='article',
            name='pingback_count',
            field=models.IntegerField(default=0, verbose_name='pingback count'),
        ),
        migrations.AddField(
            model_name='article',
            name='pingback_enabled',
            field=models.BooleanField(default=True, help_text='Allows pingbacks if checked.', verbose_name='pingbacks enabled'),
        ),
        migrations.AddField(
            model_name='article',
            name='related',
            field=models.ManyToManyField(blank=True, related_name='_article_related_+', to='articles.Article', verbose_name='related entries'),
        ),
        migrations.AddField(
            model_name='article',
            name='trackback_count',
            field=models.IntegerField(default=0, verbose_name='trackback count'),
        ),
        migrations.AddField(
            model_name='article',
            name='trackback_enabled',
            field=models.BooleanField(default=True, help_text='Allows trackbacks if checked.', verbose_name='trackbacks enabled'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=255, unique_for_date='published', verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
    ]
