# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_topic_status'),
        ('articles', '0002_auto_20161215_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.IntegerField(choices=[(20, 'Hidden'), (10, 'Draft'), (50, 'Needs approval'), (100, 'Published')], db_index=True, default=10, verbose_name='status'),
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together=set([('slug', 'topic')]),
        ),
    ]
