# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='modified',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
