# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20161213_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='modified',
            field=models.DateTimeField(null=True),
        ),
    ]
