# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_topic_organisation'),
        ('articles', '0005_auto_20161213_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='topics.Topic'),
        ),
    ]
